fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        name: "Ruff linter"
        args: [ --exit-non-zero-on-fix, --fix, --config=pyproject.toml ]
        files: '^(docling_sdg|tests).*\.(py|ipynb)$'
      - id: ruff-format
        name: "Ruff formatter"
        args: [ --config=pyproject.toml ]
        files: '^(docling_sdg|tests).*\.(py|ipynb)$'
  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        language: system
        entry: uv run mypy docling_sdg tests
        pass_filenames: false
        files: '\.py$'
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        language: system
        entry: uv run pytest tests
        pass_filenames: false
        files: '\.py$'
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.8
    hooks:
      - id: uv-lock
        name: uv lockfile
